language: rust
rust:
- stable
jobs:
  include:
  - stage: test
    script: travis_retry cargo test --workspace --release
  - stage: release crates-io
    os: linux
    if: tag IS present
    script: |
      cargo login $CRATESIO_APIKEY
      for dir in fhttp-core fhttp; do
        cd $dir
        travis_retry cargo publish
        cd -
      done
  - stage: release MacOS
    os: osx
    script: travis_retry cargo build --release --workspace && mv target/release/fhttp target/release/fhttp.macosx
    if: tag IS present
    deploy:
      provider: releases
      api_key:
        secure: bV+5NEg2BmSLzPLUlmiQuNtBW5mVDrdShF4RfjHaoxgrpb5OWieQF48YP+QHqhDM5tFM3nrwQPwpdLFbWaKqGRTz1aNUWYENKzfsZu0xvY/040ayIo0Mm5faF8vBisQLlWOrGiQaMgHa6lozSiUYZG+DSGU4yd8aCr0+iBSzmdQ35b5BatPHzzCKv5sH2jWYPqZKKeAri9m+aa00tRf4M++JNbcWheA/8Db6Yr+1WU2BCoG9ZJQktzF8D/0Tlydoh32tXMHf/WONYJIEU0LPZTST1ggyJyZ7y/K5P4wVvnaKyjEoPKc/AsFGbmwV8tV0mQ0rolku/Zret2keVI4cOwgKEoTSTRQJ8VgUp2Z2DtIO/4tSR00HUIarznuDPqYPkS0iJSzBorxFr51tP6J6pEqVsDlW0rfsg5LUxfyuPdTrMqfj5vVDZ7RoSBjg3GvPY7uOLnX7AE563uyilmEDwrdh5Pk6nKTae6dPFbVgqbNPMiqvEqVyEnkR9BsdEOAjLDy9swppeDjms01TafoDWqGJsPvQM0c0m97Bh750Wonk75SnM7jjZFd7mSq6aNU8o5w0A3BcqjCI4XI4G4sHVZDJ60/fTRH7reZm04iTuZOwWF5VVwtVyIGIwx1rkFgHpFJrHcDIOlu73qJMjq8CXysC29DxjxR6iTB0m9ewuZA=
      skip_cleanup: true
      file: target/release/fhttp.macosx
      on:
        repo: Leopard2A5/fhttp
        tags: true
  - stage: release linux x64
    os: linux
    script: travis_retry cargo build --release --workspace && mv target/release/fhttp target/release/fhttp.linux_x64
    if: tag IS present
    deploy:
      provider: releases
      api_key:
        secure: bV+5NEg2BmSLzPLUlmiQuNtBW5mVDrdShF4RfjHaoxgrpb5OWieQF48YP+QHqhDM5tFM3nrwQPwpdLFbWaKqGRTz1aNUWYENKzfsZu0xvY/040ayIo0Mm5faF8vBisQLlWOrGiQaMgHa6lozSiUYZG+DSGU4yd8aCr0+iBSzmdQ35b5BatPHzzCKv5sH2jWYPqZKKeAri9m+aa00tRf4M++JNbcWheA/8Db6Yr+1WU2BCoG9ZJQktzF8D/0Tlydoh32tXMHf/WONYJIEU0LPZTST1ggyJyZ7y/K5P4wVvnaKyjEoPKc/AsFGbmwV8tV0mQ0rolku/Zret2keVI4cOwgKEoTSTRQJ8VgUp2Z2DtIO/4tSR00HUIarznuDPqYPkS0iJSzBorxFr51tP6J6pEqVsDlW0rfsg5LUxfyuPdTrMqfj5vVDZ7RoSBjg3GvPY7uOLnX7AE563uyilmEDwrdh5Pk6nKTae6dPFbVgqbNPMiqvEqVyEnkR9BsdEOAjLDy9swppeDjms01TafoDWqGJsPvQM0c0m97Bh750Wonk75SnM7jjZFd7mSq6aNU8o5w0A3BcqjCI4XI4G4sHVZDJ60/fTRH7reZm04iTuZOwWF5VVwtVyIGIwx1rkFgHpFJrHcDIOlu73qJMjq8CXysC29DxjxR6iTB0m9ewuZA=
      skip_cleanup: true
      file: target/release/fhttp.linux_x64
      on:
        repo: Leopard2A5/fhttp
        tags: true
env:
  global:
    secure: f7Awf+zBxAzXXou7WMPX5Xm0qnFJhS0pYjf9Nc7soMOU0q7vSfz6qfxlMeu8NdcE+gR7vNiNEaEZBdd9dIKZ7jtRRLJXDatq134VEZi2B9AJHkyE4ElUqcPTaAtUqSNSrlUBdo5CNFFN3k1iVAUgzuRuedDXGWuN8jzFhYKYTGuL4t4c07Xy28tTAvEgDy4HFRL8l2BE6/CczhAGASCOhWaCmHfKr95lB6gOuwLs/zY+UI2lCGZVd4c66sLqz4J6heE+CjJH3NdN0+VZZOT0XcVjDjABnqFbZZqdK3sJIHZyNCAt4E7JYsXZvDwv7B/otx/qwCJTIAiBoqbgRGZVNKxsy0bp5852bv277c5kbHec7+6AFcubTFMTqzdC9SF1L7qCa/Wy2hOt5b2evdtYd/LdmUnjFz3cIKNSstWaJZshwJP8mNkgTVUu34oLxhMZJmE9hwD5TV+Ls73WMEzs694zwEObhHmTpxg3gkB2pjoA2SMJ9tbqgY1tVSsVhrrM9oTQpyPpKUEMgNAa8ZCrOV4fmHCzgIOo1ggDTON//6W4iTH82xoB9VbteeEiyyRTZeAGY+oEe5a0xd+Rre449pB4/FwS1saShJ0hLriGAbb7x6YPVLA03ig7gFgGqCk6+xvasz3aKhNUlyK72ZjAyMg2GgxsXOakUUHsZwuFcas=
