language: rust
rust:
- stable
jobs:
  include:
  - stage: test
    script: travis_retry cargo test --workspace --release
  - stage: release crates-io
    os: linux
    if: tag IS present
    script: |
      cargo login $CRATESIO_APIKEY
      for dir in fhttp-core fhttp; do
        cd $dir
        travis_retry cargo publish
        sleep 5
        cd -
      done
  - stage: release MacOS
    os: osx
    script: >-
      travis_retry cargo build --release --workspace
      && cd target/release
      && cp fhttp fhttp.macosx
      && tar -czf fhttp.macosx.tar.gz fhttp
      && shasum -a 256 fhttp.macos.tar.gz |cut -f1 -d ' ' > fhttp.macosx.tar.gz.sha
      && cd -
    if: tag IS present
    deploy:
      provider: releases
      api_key:
        secure: bV+5NEg2BmSLzPLUlmiQuNtBW5mVDrdShF4RfjHaoxgrpb5OWieQF48YP+QHqhDM5tFM3nrwQPwpdLFbWaKqGRTz1aNUWYENKzfsZu0xvY/040ayIo0Mm5faF8vBisQLlWOrGiQaMgHa6lozSiUYZG+DSGU4yd8aCr0+iBSzmdQ35b5BatPHzzCKv5sH2jWYPqZKKeAri9m+aa00tRf4M++JNbcWheA/8Db6Yr+1WU2BCoG9ZJQktzF8D/0Tlydoh32tXMHf/WONYJIEU0LPZTST1ggyJyZ7y/K5P4wVvnaKyjEoPKc/AsFGbmwV8tV0mQ0rolku/Zret2keVI4cOwgKEoTSTRQJ8VgUp2Z2DtIO/4tSR00HUIarznuDPqYPkS0iJSzBorxFr51tP6J6pEqVsDlW0rfsg5LUxfyuPdTrMqfj5vVDZ7RoSBjg3GvPY7uOLnX7AE563uyilmEDwrdh5Pk6nKTae6dPFbVgqbNPMiqvEqVyEnkR9BsdEOAjLDy9swppeDjms01TafoDWqGJsPvQM0c0m97Bh750Wonk75SnM7jjZFd7mSq6aNU8o5w0A3BcqjCI4XI4G4sHVZDJ60/fTRH7reZm04iTuZOwWF5VVwtVyIGIwx1rkFgHpFJrHcDIOlu73qJMjq8CXysC29DxjxR6iTB0m9ewuZA=
      skip_cleanup: true
      file:
      - target/release/fhttp.macosx
      - target/release/fhttp.macosx.tar.gz
      - target/release/fhttp.macosx.tar.gz.sha
      on:
        repo: Leopard2A5/fhttp
        tags: true
  - stage: homebrew
    if: tag IS present
    script: >-
      openssl aes-256-cbc -k "$travis_key_password" -d -md sha256 -a -in travis_key.enc -out travis_key
      && wget -O fhttp.macosx.tar.gz.sha "https://github.com/Leopard2A5/fhttp/releases/download/${TRAVIS_TAG}/fhttp.macosx.tar.gz.sha"
      && echo "Host github.com" >> ~/.ssh/config
      && echo "  IdentityFile  $(pwd)/travis_key" >> ~/.ssh/config
      && echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" >> ~/.ssh/known_hosts
      && chmod 400 travis_key
      && git clone git@github.com:Leopard2A5/homebrew-fhttp.git
      && cd homebrew-fhttp/Formula
      && sh write_formula.sh "${TRAVIS_TAG}" "$(cat fhttp.macosx.tar.gz.sha)" > fhttp.rb
      && cat fhttp.rb
      && git add fhttp.rb
      && git commit -m "release version ${TRAVIS_TAG}"
      && git push
  - stage: release linux x64
    os: linux
    script: travis_retry cargo build --release --workspace && mv target/release/fhttp
      target/release/fhttp.linux_x64
    if: tag IS present
    deploy:
      provider: releases
      api_key:
        secure: bV+5NEg2BmSLzPLUlmiQuNtBW5mVDrdShF4RfjHaoxgrpb5OWieQF48YP+QHqhDM5tFM3nrwQPwpdLFbWaKqGRTz1aNUWYENKzfsZu0xvY/040ayIo0Mm5faF8vBisQLlWOrGiQaMgHa6lozSiUYZG+DSGU4yd8aCr0+iBSzmdQ35b5BatPHzzCKv5sH2jWYPqZKKeAri9m+aa00tRf4M++JNbcWheA/8Db6Yr+1WU2BCoG9ZJQktzF8D/0Tlydoh32tXMHf/WONYJIEU0LPZTST1ggyJyZ7y/K5P4wVvnaKyjEoPKc/AsFGbmwV8tV0mQ0rolku/Zret2keVI4cOwgKEoTSTRQJ8VgUp2Z2DtIO/4tSR00HUIarznuDPqYPkS0iJSzBorxFr51tP6J6pEqVsDlW0rfsg5LUxfyuPdTrMqfj5vVDZ7RoSBjg3GvPY7uOLnX7AE563uyilmEDwrdh5Pk6nKTae6dPFbVgqbNPMiqvEqVyEnkR9BsdEOAjLDy9swppeDjms01TafoDWqGJsPvQM0c0m97Bh750Wonk75SnM7jjZFd7mSq6aNU8o5w0A3BcqjCI4XI4G4sHVZDJ60/fTRH7reZm04iTuZOwWF5VVwtVyIGIwx1rkFgHpFJrHcDIOlu73qJMjq8CXysC29DxjxR6iTB0m9ewuZA=
      skip_cleanup: true
      file: target/release/fhttp.linux_x64
      on:
        repo: Leopard2A5/fhttp
        tags: true
env:
  global:
  - secure: ASyofTYMx+U4AXnoANYt7fgP9gS2PelBAIl59XrBGnMtxl9ccfuhTfrok//q1k1YW/zAKIlkUrSlrpwNkSck3/7ifcSZ0WIBimR6B9srZ0rf7d7NSMwOF0YxuCrFhL9lkbbqWfFKtIoSJdjGhvigI0Vq+qRuoa1zmpqyZq5p2dNXb4bEXPa273YGSHYKeXLAeBTAi0O9nLfTTz7+7+q3pQKa94MScWNhqLFYb1/C3vseTKQgkzEqgW9ZgzX7MR9jixMJHJRNPBtAMMkrQpiMZv634/9/kcI5upoM172bmtXfQtFqgrSm4EosLVLOVps8lswJL0GYAWhpTa8zgQXXwGqF+EvTvHHmNKlz95K9lEyBl46Undv8+/yP05SYnvbWDlRv+O02M4VCSylmOUILYKbU503oheA6MYlLu2J1O0Kjez9oM2yPK41iL67xFcsGHuo2I2l28aW7d+vZZLa0HLHw3lSpy5xvVC2z0gk/XLspeAKreZ0Hh1r5ApskrFQib185QORbLMr2SNpeNWEVYZqfoEJCTQsbx3sxIHqXi4n/c7W+cjWT1fKgXDvrjop0kbxa8u5mbIUFlNlGOy4oKc+iOvWfDBERwlVl8raQJaOcQ8qOjOIkHQ7fyYtbnSODsEh1XyXRoF6IWWfKuMtnVKhtrx3rUmNU6T054eOLz1Q=
  - secure: E9vE2RGgJrVbskj10kZrX7joWqolkVXFkLFf5RPJXy0QxYMaABaQg5+vCQdlcERk277IT34SZ9kdsigIthU0RxlIPG/WcEo4axEutnxW/qnjnjxNjoSjVDGOIweRKaHtTWK+EQ48luNpM5VwQhu2spvoGbjTTcJD27osoZTKu2f/SGyAzsR5n+4PHAHFxDU1VL5LOQLKQ+CRqbS99PNGkvaX8AWrC+7ko1VKD8Momxa0Ij8+Si9qGBNhRytmy4rnLHL4dGRz/0djwKifBgiy0M9CH+dMKCC2fbRWy04Yac+0/185u2EvOFtcaS7wbZeRHRu1yZ3ZDLbYZ8+gxrG9Jc4uJcbH89Z3lEikmYCFWgzIUXW04uh3xzJMcIUNdlyU9C/dfsGcnF2kzS881l/aRYawJr7uvPnZ+LOY9wm5y3NV5TQmKm2xpDsGgQCbBIqsmwR9ta7ZYghfdaNdsxtyPQeay1AnpBe7LwCZY8KHqeXNRqCx7xdpSFxCUw3l4g0qpKhHxRI2h2r8Rkhk9v/qt8LXfUEcQZdXpAX9LS2qBSVkNvVlqiT1XWU8sYUTi0pnqGH2nnilVnXJk+ACqLOTxmKFpmaG8SHUCBlbIuyJm9FcVxmuxvnmZCa+yHE6SDVFfSGTq++bz5H/tnBx4timwSRAXYVpXpzXIgQQTpqSm1k=
