language: rust
rust:
- stable
jobs:
  include:
  - stage: test
    script: travis_retry cargo test --workspace --release
  - stage: release crates-io
    os: linux
    if: tag IS present
    script: |
      cargo login $CRATESIO_APIKEY
      for dir in fhttp-core fhttp; do
        cd $dir
        travis_retry cargo publish
        sleep 5
        cd -
      done
  - stage: release MacOS
    os: osx
    script: travis_retry cargo build --release --workspace && mv target/release/fhttp target/release/fhttp.macosx
    if: tag IS present
    deploy:
      provider: releases
      api_key:
        secure: bV+5NEg2BmSLzPLUlmiQuNtBW5mVDrdShF4RfjHaoxgrpb5OWieQF48YP+QHqhDM5tFM3nrwQPwpdLFbWaKqGRTz1aNUWYENKzfsZu0xvY/040ayIo0Mm5faF8vBisQLlWOrGiQaMgHa6lozSiUYZG+DSGU4yd8aCr0+iBSzmdQ35b5BatPHzzCKv5sH2jWYPqZKKeAri9m+aa00tRf4M++JNbcWheA/8Db6Yr+1WU2BCoG9ZJQktzF8D/0Tlydoh32tXMHf/WONYJIEU0LPZTST1ggyJyZ7y/K5P4wVvnaKyjEoPKc/AsFGbmwV8tV0mQ0rolku/Zret2keVI4cOwgKEoTSTRQJ8VgUp2Z2DtIO/4tSR00HUIarznuDPqYPkS0iJSzBorxFr51tP6J6pEqVsDlW0rfsg5LUxfyuPdTrMqfj5vVDZ7RoSBjg3GvPY7uOLnX7AE563uyilmEDwrdh5Pk6nKTae6dPFbVgqbNPMiqvEqVyEnkR9BsdEOAjLDy9swppeDjms01TafoDWqGJsPvQM0c0m97Bh750Wonk75SnM7jjZFd7mSq6aNU8o5w0A3BcqjCI4XI4G4sHVZDJ60/fTRH7reZm04iTuZOwWF5VVwtVyIGIwx1rkFgHpFJrHcDIOlu73qJMjq8CXysC29DxjxR6iTB0m9ewuZA=
      skip_cleanup: true
      file: target/release/fhttp.macosx
      on:
        repo: Leopard2A5/fhttp
        tags: true
  - stage: release linux x64
    os: linux
    script: travis_retry cargo build --release --workspace && mv target/release/fhttp target/release/fhttp.linux_x64
    if: tag IS present
    deploy:
      provider: releases
      api_key:
        secure: bV+5NEg2BmSLzPLUlmiQuNtBW5mVDrdShF4RfjHaoxgrpb5OWieQF48YP+QHqhDM5tFM3nrwQPwpdLFbWaKqGRTz1aNUWYENKzfsZu0xvY/040ayIo0Mm5faF8vBisQLlWOrGiQaMgHa6lozSiUYZG+DSGU4yd8aCr0+iBSzmdQ35b5BatPHzzCKv5sH2jWYPqZKKeAri9m+aa00tRf4M++JNbcWheA/8Db6Yr+1WU2BCoG9ZJQktzF8D/0Tlydoh32tXMHf/WONYJIEU0LPZTST1ggyJyZ7y/K5P4wVvnaKyjEoPKc/AsFGbmwV8tV0mQ0rolku/Zret2keVI4cOwgKEoTSTRQJ8VgUp2Z2DtIO/4tSR00HUIarznuDPqYPkS0iJSzBorxFr51tP6J6pEqVsDlW0rfsg5LUxfyuPdTrMqfj5vVDZ7RoSBjg3GvPY7uOLnX7AE563uyilmEDwrdh5Pk6nKTae6dPFbVgqbNPMiqvEqVyEnkR9BsdEOAjLDy9swppeDjms01TafoDWqGJsPvQM0c0m97Bh750Wonk75SnM7jjZFd7mSq6aNU8o5w0A3BcqjCI4XI4G4sHVZDJ60/fTRH7reZm04iTuZOwWF5VVwtVyIGIwx1rkFgHpFJrHcDIOlu73qJMjq8CXysC29DxjxR6iTB0m9ewuZA=
      skip_cleanup: true
      file: target/release/fhttp.linux_x64
      on:
        repo: Leopard2A5/fhttp
        tags: true
env:
  global:
    secure: ASyofTYMx+U4AXnoANYt7fgP9gS2PelBAIl59XrBGnMtxl9ccfuhTfrok//q1k1YW/zAKIlkUrSlrpwNkSck3/7ifcSZ0WIBimR6B9srZ0rf7d7NSMwOF0YxuCrFhL9lkbbqWfFKtIoSJdjGhvigI0Vq+qRuoa1zmpqyZq5p2dNXb4bEXPa273YGSHYKeXLAeBTAi0O9nLfTTz7+7+q3pQKa94MScWNhqLFYb1/C3vseTKQgkzEqgW9ZgzX7MR9jixMJHJRNPBtAMMkrQpiMZv634/9/kcI5upoM172bmtXfQtFqgrSm4EosLVLOVps8lswJL0GYAWhpTa8zgQXXwGqF+EvTvHHmNKlz95K9lEyBl46Undv8+/yP05SYnvbWDlRv+O02M4VCSylmOUILYKbU503oheA6MYlLu2J1O0Kjez9oM2yPK41iL67xFcsGHuo2I2l28aW7d+vZZLa0HLHw3lSpy5xvVC2z0gk/XLspeAKreZ0Hh1r5ApskrFQib185QORbLMr2SNpeNWEVYZqfoEJCTQsbx3sxIHqXi4n/c7W+cjWT1fKgXDvrjop0kbxa8u5mbIUFlNlGOy4oKc+iOvWfDBERwlVl8raQJaOcQ8qOjOIkHQ7fyYtbnSODsEh1XyXRoF6IWWfKuMtnVKhtrx3rUmNU6T054eOLz1Q=
