on: [push]

jobs:
  test:
    name: test
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: test
        run: for i in 1 2 3; do cargo test --workspace && break; done
